### ISSUE TITLE
Migrate to Hardhat Configuration Variables

### ISSUE THREAD

**Issue by nlordell** [safe-global/safe-modules#152]
## Description

Currently, the project uses `.env` files for configuration, but Hardhat recommends using configuration variables (helps protect against accidentally committing and pushing a `.env` file with secrets, and also makes sharing across Hardhat projects seamless - so no need to copy `.env` configuration files around).

## Additional context

<https://hardhat.org/hardhat-runner/docs/guides/configuration-variables#migrating-from--dotenv>

**Comment by mmv08** [comment]
> Does this mean that any hardhat project that I run on my computer has access to these variables? If this is the case is it really more secure than a `.env` file that is local to one repository?

I tested it and it stored the files in `/Users/mmv/Library/Preferences/hardhat-nodejs/vars.json` without any indication of the project they belong to:
```
{
  "_format": "hh-vars-1",
  "vars": {
    "TEST_API_KEY": {
      "value": "test"
    }
  }
}
```

Doesn't sound good to me

**Comment by nlordell** [comment]
Closing as "wont-fix" then.
