### ISSUE TITLE
[4337] Evaluating enabling yul optimizer and viaIR for Safe 4337 Module

### ISSUE THREAD

**Issue by mmv08** [safe-global/safe-modules#153]
The same issue as in safe-contracts: https://github.com/safe-global/safe-contracts/issues/544

If you enabled IR to compile the module, it won't compile because it imports the Safe contracts

**Comment by remedcu** [comment]
It was decided to use `v0.8.23` instead of `v0.8.19` for this issue.

**Comment by remedcu** [comment]
Enabling `viaIR` for the Safe 4337 Module results in vendoring some contracts from the `safe-contract` with some `memory-safe` and compatibility changes in the `v1.4.1`. This results in some gas savings, but not enough, making it worth the change.

More details can be found in this [description](https://github.com/safe-global/safe-modules/pull/207#issue-2082187638) of the PR which evaluated the change.
