### ISSUE TITLE
Using Reference `EntryPoint` for Gas Metering

### ISSUE THREAD

**Issue by remedcu** [safe-global/safe-modules#211]
## Description

4337 Gas Metering uses `TestEntryPoint` instead of `ReferenceEntryPoint`. For accurate gas measurement, using the latter is ideal.

**Comment by nlordell** [comment]
It is also important when comparing to other implementations since they will likely be metered against the reference `EntryPoint` contract (otherwise we would be comparing apples to oranges).

**Comment by nlordell** [comment]
Superseded by #226
