### ISSUE TITLE
Use the production entrypoint contract for testing

### ISSUE THREAD

**Issue by mmv08** [safe-global/safe-modules#226]
As discussed internally, there are potential benefits to using the production version of the entry point contract for testing. We already do that for e2e testing, but the integration tests use a mock. This is the improvement we want for the upcoming release of 0.7.0 entrypoint compatibility.

Deliverables:
- Refactoring the tests to use the entrypoint 0.7.0 everywhere

Potential blockers:
- I'm not sure if the entrypoint contract 0.7.0 is available in package repositories like npm, may need to get creative with fetching it

**Comment by nlordell** [comment]
Related to #211
