### ISSUE TITLE
Update end-to-end tests with 0.7.0 entrypoint & corresponding bundler

### ISSUE THREAD

**Issue by mmv08** [safe-global/safe-modules#227]
For the upcoming release of 0.7.0 entrypoint compatibility, we want our end-to-end tests to use the 0.7.0 entrypoint and a bundler version supporting it.

Deliverables:
- Refactoring end-to-end tests to use the entrypoint and bundler 0.7.0

Potential blockers:
- Bundler image/entrypoint may be unavailable due to undergoing security audit

**Comment by nlordell** [comment]
I removed it from the current iteration.

**Comment by mmv08** [comment]
This is blocked by the release of the production bundler & entrypoint version, isn't it? We added an e2e job that uses the upstream version of the bundler and the entrypoint and we should keep an eye on it. I am not sure if it makes sense to include it in the current iteration
