### ISSUE TITLE
Update `4337-gas-metering/pimlico` ERC20 Paymaster to use `v0.7 EntryPoint`

### ISSUE THREAD

**Issue by remedcu** [safe-global/safe-modules#294]
The current version uses `v0.6 EntryPoint` for gas metering. As the latest version is released, it is best to use the newest version for Gas Analysis.

# Potential issues
- The last time we attempted to benchmark the ERC20 Paymaster, we couldn't get enough USDC tokens supported by the Paymaster. The faucet drips 10 USDC daily, and one user operation costs 6-7 USDC on Base Sepolia and 530 USDC on Sepolia. It doesn't have any liquidity, either.

## Expected Outcome
- Using `v0.7` EntryPoint with the compatible Safe 4337 Module and Pimlico ERC20 Paymaster
- Table containing gas usage with Safe 4337 Module and Pimlico ERC20 Paymaster

**Comment by remedcu** [comment]
As Pimlico is still working on their `paymaster`, this task cannot be completed within the current iteration (12). The intermediate state is pushed to the branch: [pimlico-4337-gas-metering](https://github.com/safe-global/safe-modules/tree/pimlico-4337-gas-metering)

**Comment by nlordell** [comment]
Currently blocked because of Pimlico paymaster issues.
