### ISSUE TITLE
Add a proper documentation to the `Safe256BitECSignerLaunchpad` contract

### ISSUE THREAD

**Issue by mmv08** [safe-global/safe-modules#308]
## Context / issue

The migration of the experimental `Safe256BitECSignerLaunchpad` contract in https://github.com/safe-global/safe-modules/pull/306 wasn't complete. It missed `NatSpec` and a proper testing suite.

## Proposed solution

- Complete the `NatSpec` documentation

## Alternatives

- Since the contract is not "mandatory" for the release of the passkey signer, we can also make it explicitly experimental and not include it in the release/audit scope

**Comment by nlordell** [comment]
The work to add 100% test coverage to the launchpad contract was moved to #380 as it is blocked on #372 and #377

**Comment by rmeissner** [comment]
Should this issue be closed @nlordell ?

**Comment by nlordell** [comment]
Yes it can
