### ISSUE TITLE
E2E Test With P-256 Precompile

### ISSUE THREAD

**Issue by nlordell** [safe-global/safe-modules#317]
Follow up to #285, once running an execution client that supports the P-256 precompile is easier, an E2E test that the WebAuthn signer supports the precompile contract should be added. We expect to use `bor` when the dev mode issue is resolved. 

### Expected Outcome

And E2E test that spins up a local dev node with the P-256 precompile and a test that verifies that WebAuthn signature verification works as expected.

**Comment by nlordell** [comment]
This is blocked on us finding a developer node that is compatible with the reference bundler and supports the 7212 pre-compile. The primary candidate is `bor` (Polygon node), but its `-dev` mode currently does not enable EIP-7212.

**Comment by mmv08** [comment]
ZkSync added support for the precompile in their recent release: https://github.com/zkSync-Community-Hub/zksync-developers/discussions/519

I tested in the [dockerized](https://docs.zksync.io/build/test-and-debug/dockerized-l1-l2-nodes.html) node and it seems to pass the test from RIP-7212's reference implementation.

```
curl --location 'http://localhost:3050' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [{"to": "0x0000000000000000000000000000000000000100", "data": "0x4cee90eb86eaa050036147a12d49004b6b9c72bd725d39d4785011fe190f0b4da73bd4903f0ce3b639bbbf6e8e80d16931ff4bcf5993d58468e8fb19086e8cac36dbcd03009df8c59286b162af3bd7fcc0450c9aa81be5d10d312af6c66b1d604aebd3099c618202fcfe16ae7770b0c49ab5eadf74b754204a3bb6060e44eff37618b065f9832de4ca6ca971a7a1adc826d0f7c00181a5fb2ddf79ae00b4e10e"} ],
    "id": 1
}'
```

```
{
    "jsonrpc": "2.0",
    "result": "0x0000000000000000000000000000000000000000000000000000000000000001",
    "id": 1
}
```

**Comment by nlordell** [comment]
Oh man, I didn't realize but this requires us to build our contracts for zkSync which is a bit more than I intended to work on for this PR.
