### ISSUE TITLE
Add Comprehensive Passkey Sample Application

### ISSUE THREAD

**Issue by akshay-ap** [safe-global/safe-modules#330]
We should add a new package in the `examples/` directory with passkey support similar to the base wallet example application in:

https://www.smart-wallet.xyz/

## Expected Outcome

Either a new package in the `examples/` directory, or reuse the existing `examples/4337-passkey` package to make a demo application using passkey support with similar features/documentation/niceties as the Coinbase wallet demo app. Notable things that are missing:

- [ ] Ability to interact with the Wallet once it is deployed (the demo app from Coinbase has a "mint" button that causes the account to mint things)
- [ ] FAQ section with comprehensive documentation

**Comment by mmv08** [comment]
Closing in favour of more targeted issues: https://github.com/safe-global/safe-modules/issues/360 and https://github.com/safe-global/safe-modules/issues/361
