### ISSUE TITLE
Setup NPM Package For Recovery Module

### ISSUE THREAD

**Issue by nlordell** [safe-global/safe-modules#350]
This issue captures the work for setting up a new NPM workspace package for the Passkey contracts.

The new package should include basic CI items:
- Empty `hardhat` setup
- Formatting and linting
- Testing (although, this can be a no-op at first)

**Comment by remedcu** [comment]
Closed due to: https://github.com/safe-global/safe-modules/pull/383#issuecomment-2069197313
