### ISSUE TITLE
Publish NPM Package for 4337 and Passkey Module

### ISSUE THREAD

**Issue by nlordell** [safe-global/safe-modules#351]
Currently, user stories depend on unpublished code in the `modules/4337` and `modules/passkey` packages in order to work.

We should publish these packages to the NPM registry in order to facilitate the use of the 4337 and passkey modules.

## Expected Outcome

- [ ] The code required to make the user story demos work (notably, extracting public key from a WebAuthn response and encoding the WebAuthn signer signature) should move to the `src/` tree (out of the `test/` tree)
- [ ] Both `modules/4337` and `modules/passkey` packages should be published to the public NPM registry (npmjs.org).

**Comment by rmeissner** [comment]
Can this issue be closed @nlordell
