### ISSUE TITLE
Specification for External Module Vetting Process

### ISSUE THREAD

**Issue by nlordell** [safe-global/safe-modules#352]
This issue involves the work associated with vetting an external module/contract to be reused by the Safe Contracts and the process involved to do the same.

Some of the things which can be considered for the process are:
- Product Requirement Satisfaction
- Internal Audit & Review
- Additional Testing
- Formal Verification
- Additional Auditing

**Comment by remedcu** [comment]
An internal document which specified the "External Module Vetting Process" has been created.
