### ISSUE TITLE
Ambigious behaviour with WebAuthn shim

### ISSUE THREAD

**Issue by remedcu** [safe-global/safe-modules#369]
## Description

The test "Should authorise and verify an existing credential" in the `WebAuthn Shim` section fails unexpectedly ([Source](https://github.com/safe-global/safe-modules/actions/runs/8597366623/job/23555916815))

## Steps to reproduce

This fails rarely, as the next run of the job returns `true`.

## Additional context

The problem was found during changes created in PR #356 (though no change in the concerned file was made).

**Comment by nlordell** [comment]
Uploading the log archive in case GitHub decides to delete the run.

[logs_22525924257.zip](https://github.com/safe-global/safe-modules/files/14903634/logs_22525924257.zip)

**Comment by remedcu** [comment]
Another failure, this time with the `e2e` CI script.

Log Link: https://github.com/safe-global/safe-modules/actions/runs/9990468990/job/27611219692
Log Archive: 
[logs_26151611198.zip](https://github.com/user-attachments/files/16282463/logs_26151611198.zip)

**Comment by nlordell** [comment]
I think that is an unrelated issue @remedcu, in fact the WebAuthn shim does not appear to be used in the failing test - it is just taking a little more gas than expected.

**Comment by mmv08** [comment]
what a legend
