### ISSUE TITLE
Evaluate Product Requirements for Multi Owner Accounts with Passkeys

### ISSUE THREAD

**Issue by mmv08** [safe-global/safe-modules#391]

**Comment by mmv08** [comment]
After the requirements are figured out, we should revisit https://github.com/safe-global/safe-modules/issues/361

**Comment by nlordell** [comment]
I think it's figured out in Slack and just needs to be reflected here (cc @akshay-ap )

**Comment by akshay-ap** [comment]
After discussing with the product team, we conclude that Multi-owner accounts with passkeys should be supported.

It should be possible to have following setups:
- Safe with 4337 support for 1/1 signer
- Safe with 4337 support for 2/n signers using passkey + other arbitrary signers

This should be supported by the SDK. To enable such setup, `SafeSignerLaunchpad` contract needs to be refactored such that when deploying a Safe, multiple-owners can be set and does not need re-work to update the Safe owners.

https://github.com/safe-global/safe-modules/blob/fbce8f1bc7d4e5183c291f62e07a30648cc70943/modules/passkey/contracts/4337/SafeSignerLaunchpad.sol#L261

**Comment by nlordell** [comment]
I would also add, that for the _initial release_ a 1/n Safe with using passkey + other arbitrary signers is all that is needed (i.e. we do not need to support `threshold != 1`).

**Comment by akshay-ap** [comment]
> I would also add, that for the _initial release_ a 1/n Safe with using passkey + other arbitrary signers is all that is needed (i.e. we do not need to support `threshold != 1`).
> 
> > with passkeys should be supported
> 
> MUST be supported.
> 
> > Safe can be re-assigned ownership configuration but this is not an ideal approach.
> 
> I think we should mention that this is not secure (the account is a 1/n Safe for the first transaction).

done
