### ISSUE TITLE
Add a way to add a recovery signers to the example passkey app

### ISSUE THREAD

**Issue by mmv08** [safe-global/safe-modules#392]
Currently, the example application is missing a way to add a recovery signer to prevent passkeys from being a single point of failure.

The goal of this issue is to provide a way to add a recovery signer to the account AFTER it has been created. Creating an account with a recovery signer is out of scope until https://github.com/safe-global/safe-modules/issues/372 is figured out

**Comment by nlordell** [comment]
Implemented sometime in the past.
