### ISSUE TITLE
Module.sol import is missing on recurring transfer module

### ISSUE THREAD

**Issue by alresarena2021** [safe-global/safe-modules#45]
@gnosis.pm/safe-contracts/contracts/base/Module.sol  is missing on recurring transfer module

**Comment by lowellyc** [comment]
> @gnosis.pm/safe-contracts/contracts/base/Module.sol is missing on recurring transfer module

it is removed on this PR commit: https://github.com/gnosis/safe-contracts/pull/256/commits/db647fd40b5ffa714f6900642ad2739169a65533
