### ISSUE TITLE
Use Safe Singleton Factory for Deployments

### ISSUE THREAD

**Issue by nlordell** [safe-global/safe-modules#473]
## Context / issue

Currently, all our deployments are done using the CREATE2 deployer at `0x4e59b44847b379578588920ca78fbf26c0b4956c`. We should change our modules to use the Safe singleton factory, just like we do for our core contracts.

Affected modules:
- 4337
- Passkeys
- Recovery
- Allowance

Make sure to update the expected address and include this in the `CHANGELOG` for the respective projects.

**Comment by remedcu** [comment]
Closed by #477
