### ISSUE TITLE
[4337 Module] Coordinate external audit

### ISSUE THREAD

**Issue by rmeissner** [safe-global/safe-modules#84]
Contract to be audited:
- Module/Fallback handler
- Deployment utility contracts (i.e. library or factorY)
- Document technical details and usage
  - Security considerations

**Comment by mmv08** [comment]
Just documenting here that it might depend on https://github.com/safe-global/safe-modules/issues/87

**Comment by joaoavf** [comment]
Hey, great to see this taking shape! We are considering using the 4337 module in our product - curious to know if you have a sense of timelines for a stable version of the code and for the audit. 

(I understand things might be quite uncertain at this moment - but appreciate a general overview on it - and sorry if this is not the best forum to ask this question)

**Comment by nlordell** [comment]
Just to document here that the audit was kicked off.

**Comment by nlordell** [comment]
@joaoavf - the audit was concluded and the findings were added in #139
