### ISSUE TITLE
[4337 Module] Increase test coverage to 99+%

### ISSUE THREAD

**Issue by rmeissner** [safe-global/safe-modules#87]
- Update hardhat version
- All branches need to be covered
- (optional) Add separate tests using latest bytecode for entrypoint on official address

**Comment by nlordell** [comment]
Updating hardhat version being worked on in #100
Reduced code to cover in #104

**Comment by nlordell** [comment]
Looks like GitHub auto-closed this issue with the #108 PR ("partially fixes $ISSUE" is interpreted as "fixes $ISSUE") 🙈.

**Comment by nlordell** [comment]
Closing as the required tasks are implemented. The good to have isn't quite done, but there is a draft PR open for it.
